### ISSUE TITLE
Where do I get generate_parameter_library_py?

### ISSUE THREAD

**Issue by Guelakais** [PickNikRobotics/generate_parameter_library#147]
I have tried to use the tutorial, but I don't understand how to use the Python library generate_parameter_library_py. Installing pip doesn't work. So what should I do?

**Comment by Guelakais** [comment]
edit: installing it with pip doesn't work. That's what I meant

**Comment by christophfroehlich** [comment]
you can install it via apt, it's called `ros-${ROS_DISTRO}-generate-parameter-library-py` or let rosdep do that for your package.

**Comment by Guelakais** [comment]
thanks
