### ISSUE TITLE
Changing parameter declaration

### ISSUE THREAD

**Issue by edwardribbit** [PickNikRobotics/generate_parameter_library#189]
When I change a parameter declaration file, colcon clean, and rebuild the package, it seems like the changes have no effect.

'x' has invalid type: Wrong parameter type, parameter {x} is of type {double}, setting it to {integer} is not allowed.

I change the parameter type from double to int in the declaration file, clean, build, and rerun but this error still appears.
I even delete the build and install folder.

How can I clean my environment to update the parameter declaration?

**Comment by pac48** [comment]
@edwardribbit Can you post your `parameters.yaml` file used by `generate_parameter_library` to generate the code? Or at least post the section you think is causing the issue.
