### ISSUE TITLE
Jazzy/Rolling release please?

### ISSUE THREAD

**Issue by bmagyar** [PickNikRobotics/generate_parameter_library#209]
We can send :cookie:

**Comment by bmagyar** [comment]
@pac48 I'm not sure who to tag for this request.

**Comment by christophfroehlich** [comment]
@pac48 or @sea-bass maybe?

**Comment by sea-bass** [comment]
Thanks for the tag, @christophfroehlich -- I'll get to this!

**Comment by sea-bass** [comment]
Thanks @jafarabdi for the assist!

* Rolling: https://github.com/ros/rosdistro/pull/43277
* Jazzy: https://github.com/ros/rosdistro/pull/43278
* Iron: https://github.com/ros/rosdistro/pull/43279
* Humble: https://github.com/ros/rosdistro/pull/43280

All lined up for a release on the next sync.

**Comment by bmagyar** [comment]
Grand! Thank you guys!

**Comment by sea-bass** [comment]
I like white chocolate macadamia, by the way :)
