### ISSUE TITLE
Undeclaring a parameter throws an unexpected error.

### ISSUE THREAD

**Issue by pac48** [PickNikRobotics/generate_parameter_library#21]
According to the ROS 2 documentation, the `undeclare_parameter(const std::string & name)` method of `rclcpp::node_interfaces::NodeParametersInterface` should only throw two types of exceptions:

1. `rclcpp::exceptions::ParameterNotDeclaredException`: if the parameter has not been declared.
2. `rclcpp::exceptions::ParameterImmutableException`:  if the parameter was create as read_only (immutable).

I get the following exception when I try to undeclare a parameter.
```
terminate called after throwing an instance of 'rclcpp::exceptions::InvalidParameterTypeException'
  what():  parameter 'pid.elbow_joint.p' has invalid type: cannot undeclare an statically typed parameter
```
This  occurs when setting the parameter like this:
```
double val = 1.5;
auto parameter = rclcpp::ParameterValue(val);
rcl_interfaces::msg::ParameterDescriptor descriptor;
descriptor.description = "my  parameter";
parameters_interface_->declare_parameter("pid.elbow_joint.p", parameter, descriptor);
```

**Comment by tylerjw** [comment]
I believe this is expected behavior as undeclaring only works on dynamically typed parameters.
