### ISSUE TITLE
ros-foxy-generate-parameter-library

### ISSUE THREAD

**Issue by SPoof-oss** [PickNikRobotics/generate_parameter_library#225]
lx@LXOS:~$ sudo apt install ros-foxy-generate-parameter-library
[sudo] lx's password: 
Reading package list... finish
The dependency tree of the package is being analyzed       
Reading status information... finish       
E: Unable to locate package ros-foxy-generate-parameter-library

This installation package always fails to be installed successfully. git clone, there are all kinds of errors

CMake Error at /home/lx/generate_parameter_library-main/install/generate_parameter_library/share/generate_parameter_library/cmake/generate_parameter_library.cmake:115 (ament_get_python_install_dir):
  Unknown CMake command "ament_get_python_install_dir".
Call Stack (most recent call first):
  CMakeLists.txt:8 (generate_parameter_module)

**Comment by sea-bass** [comment]
If you look at the ROS Package Index (https://index.ros.org/search/?term=generate_parameter_library), you'll see there is no Foxy release. This package came out in Humble.

Anyways, Foxy's been end of life for about a year, so I don't think new packages are even possible to release at this time. I suggest you upgrade to a currently supported ROS distro, or build this package from source in your Foxy workspace if absolutely needed.
