### ISSUE TITLE
Will you release this library?

### ISSUE THREAD

**Issue by hakuturu583** [PickNikRobotics/generate_parameter_library#65]
I think your work looks great.
Will you release this library in ros buildfarm?

**Comment by tylerjw** [comment]
It is released for rolling and humble: https://index.ros.org/p/generate_parameter_library/

I plan on making another release with the latest bug fixes and features in a couple of weeks.

**Comment by tylerjw** [comment]
- https://github.com/ros/rosdistro/pull/34589
- https://github.com/ros/rosdistro/pull/34600

**Comment by nikolaseu** [comment]
Hey Tyler, can you release 0.3.1 for humble?
We would really like to generate the `*_parameters.hpp` header in `include/<package>/`

**Comment by ChrisThrasher** [comment]
https://github.com/ros/rosdistro/pull/36255

0.3.1 is on the way for Humble and Rolling
