### ISSUE TITLE
Option to print parameter values

### ISSUE THREAD

**Issue by diogoalmeida** [PickNikRobotics/generate_parameter_library#86]
I have been using this library and I am really happy with it - thanks for the contribution!

This issue is more of a question/feature request: can we log the parameters that are loaded by the parameter listener? This would be very useful for debugging purposes.

**Comment by tylerjw** [comment]
Would it help if we used ROS logging and sent it to a debug level? Then you could enable it if you want to see them.

**Comment by diogoalmeida** [comment]
Absolutely @tylerjw , that would be amazing :)

**Comment by tylerjw** [comment]
I'm not sure when I'll get to this, but I will add it to the list of things I'll do next on this project. It might be a couple of weeks as I'm going on vacation tomorrow.

**Comment by diogoalmeida** [comment]
thanks for welcoming the feature request, and have a great time off :)

**Comment by tylerjw** [comment]
@diogoalmeida I'm sorry it took me so long to get around to this. I just submitted a PR to build this feature. I would appreciate a review if you have time?

**Comment by diogoalmeida** [comment]
Hey Tyler, thanks so much for being able to implement this feature. This is exciting :D 

I will definitely give you a review and try it out in our system as soon as possible. 

Once again, many thanks.
